export const LOAD_USER_STORAGE = 'STORAGE/LOAD_USER_STORAGE';
export const UPDATE_USER_STORAGE = 'STORAGE/UPDATE_USER_STORAGE';
export const LOAD_TRADE_OFFERS = 'MARKET/LOAD_TRADE_OFFERS';
export const UPDATE_TRADE_OFFERS = 'MARKET/UPDATE_TRADE_OFFERS';