export const LOAD_LAW_TYPES = 'PARLIAMENT/LOAD_LAW_TYPES';
export const LOAD_PARLIAMENTARIANS = 'PARLIAMENT/LOAD_PARLIAMENTARIANS';
export const LOAD_COUNTRY = 'COUNTRY/LOAD_COUNTRY';
export const LOAD_ELECTIONS = 'COUNTRY/LOAD_ELECTIONS';
export const SET_LOADING = 'COUNTRY/SET_LOADING';
