export const LOAD_LAW_TYPES = 'PARLIAMENT/LOAD_LAW_TYPES';
export const LOAD_ACTIVE_LAWS = 'PARLIAMENT/LOAD_ACTIVE_LAWS';
export const LOAD_PARLIAMENTARIANS = 'PARLIAMENT/LOAD_PARLIAMENTARIANS';
export const LOAD_COUNTRY = 'COUNTRY/LOAD_COUNTRY';
export const LOAD_PRESIDENT_ELECTION = 'COUNTRY/LOAD_PRESIDENT_ELECTION';
export const LOAD_PARTY_ELECTION = 'COUNTRY/LOAD_PARTY_ELECTION';
export const LOAD_PARLIAMENT_ELECTION = 'COUNTRY/LOAD_PARLIAMENT_ELECTION';
export const SET_LOADING = 'COUNTRY/SET_LOADING';
