export const SET_SELECTED_REGION = 'WORLD_MAP/SET_SELECTED_REGION';
export const SET_MOVING_TO_REGION = 'WORLD_MAP/SET_MOVING_TO_REGION';
export const CLEAR_MOVING_TO_REGION = 'WORLD_MAP/CLEAR_MOVING_TO_REGION';