export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ERROR_MESSAGE = 'APP/SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'APP/HIDE_ERROR_MESSAGE';

export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_UP = 'AUTH/SIGN_UP';
export const SIGN_OUT = 'AUTH/SIGN_OUT';
export const CLEAR_USER = 'AUTH/CLEAR_USER';
export const ME = 'AUTH/ME';

export const CREATE_ACTION = 'USER/CREATE_ACTION';

export const LOAD_RECOMMENDED_ARTICLES = 'NEWS/LOAD_RECOMMENDED_ARTICLES';
export const LOAD_TOP_ARTICLES = 'NEWS/LOAD_TOP_ARTICLES';
export const LOAD_PROMOTED_ARTICLE = 'NEWS/LOAD_PROMOTED_ARTICLE';
export const LOAD_SUBSCRIPTION_ARTICLES = 'NEWS/LOAD_SUBSCRIPTION_ARTICLES';
export const GET_SUBSCRIPTION_ARTICLES_PAGE = 'NEWS/GET_SUBSCRIPTION_ARTICLES_PAGE';
export const LOAD_MY_NEWSPAPER = 'NEWS/LOAD_MY_NEWSPAPER';

export const LOAD_LAST_ARTICLES = 'NEWS/LOAD_LAST_ARTICLES';
export const GET_LAST_ARTICLES_PAGE = 'NEWS/GET_LAST_ARTICLES_PAGE';

export const LOAD_ARTICLE = 'NEWS/LOAD_ARTICLE';
export const LOAD_COMMENTS = 'NEWS/COMMENTS';
export const UPDATE_ARTICLE_RATING = 'NEWS/UPDATE_ARTICLE_RATING';
