export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_UP = 'AUTH/SIGN_UP';
export const SIGN_OUT = 'AUTH/SIGN_OUT';
export const CLEAR_USER = 'AUTH/CLEAR_USER';
export const ME = 'AUTH/ME';
export const SHOW_ERROR_MESSAGE = 'APP/SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'APP/HIDE_ERROR_MESSAGE';

export const CLEAR_WAR_ACTION = 'USERS/CLEAR_WAR_ACTION';
export const CLEAR_WORK_ACTION = 'USERS/CLEAR_WORK_ACTION';
export const CLEAR_MOVE_ACTION = 'USERS/CLEAR_MOVE_ACTION';
export const SET_WORK_ACTION = 'USERS/SET_WORK_ACTION';
export const SET_WAR_ACTION = 'USERS/SET_WAR_ACTION';
export const SET_MOVE_ACTION = 'USERS/SET_MOVE_ACTION';

export const CLEAR_JOB = 'USER/CLEAR_JOB';
export const SET_JOB = 'USERS/SET_JOB';