export const LOAD_USER = 'USERS/LOAD_USER';

export const SET_SELECTED_AVATAR_FILE = 'USERS/FORM/SET_SELECTED_AVATAR_FILE';
export const SET_PREVIEW_AVATAR_FILE = 'USERS/FORM/SET_PREVIEW_AVATAR_FILE';
export const SET_CROPPED_AVATAR_FILE = 'USERS/FORM/SET_CROPPED_AVATAR_FILE';