export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SET_LOADER = 'APP/SET_LOADER';

export const HIDE_DRAWER = 'APP/HIDE_DRAWER';
export const SHOW_DRAWER = 'APP/SHOW_DRAWER';

export const SET_PRIMARY_COLOR = 'APP/SET_PRIMARY_COLOR';
export const SET_SECONDARY_COLOR = 'APP/SET_SECONDARY_COLOR';