export const LOAD_RECOMMENDED_ARTICLES = 'NEWS/LOAD_RECOMMENDED_ARTICLES';
export const LOAD_TOP_ARTICLES = 'NEWS/LOAD_TOP_ARTICLES';
export const LOAD_PROMOTED_ARTICLE = 'NEWS/LOAD_PROMOTED_ARTICLE';
export const LOAD_SUBSCRIPTION_ARTICLES = 'NEWS/LOAD_SUBSCRIPTION_ARTICLES';
export const GET_SUBSCRIPTION_ARTICLES_PAGE = 'NEWS/GET_SUBSCRIPTION_ARTICLES_PAGE';

export const LOAD_LAST_ARTICLES = 'NEWS/LOAD_LAST_ARTICLES';
export const GET_LAST_ARTICLES_PAGE = 'NEWS/GET_LAST_ARTICLES_PAGE';
