export const UPDATE_SUBSCRIPTION = 'NEWSPAPER/UPDATE_SUBSCRIPTION';
export const LOAD_NEWSPAPER = 'NEWSPAPER/LOAD_NEWSPAPER';
export const LOAD_STAFF = 'NEWSPAPER/LOAD_STAFF';
export const UPDATE_STAFF = 'NEWSPAPER/UPDATE_STAFF';