export const UPDATE_SUBSCRIPTION = 'NEWSPAPER/UPDATE_SUBSCRIPTION';
export const LOAD_NEWSPAPER = 'NEWSPAPER/LOAD_NEWSPAPER';
export const LOAD_STAFF = 'NEWSPAPER/LOAD_STAFF';
export const UPDATE_STAFF = 'NEWSPAPER/UPDATE_STAFF';

export const LOAD_ARTICLES = 'NEWSPAPER/LOAD_ARTICLES';
export const GET_ARTICLES_PAGE = 'NEWSPAPER/GET_ARTICLES_PAGE';