export const LOAD_PARTIES = 'PARTY/LOAD_PARTIES';
export const UPDATE_PARTIES = 'PARTY/UPDATE_PARTIES';
export const LOAD_REQUESTS = 'PARTY/LOAD_REQUESTS';
export const ACCEPT_REQUEST = 'PARTY/ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'PARTY/DECLINE_REQUEST';
export const LOAD_STAFF = 'PARTY/LOAD_STAFF';
export const UPDATE_STAFF = 'PARTY/UPDATE_STAFF';

export const SET_LOADING = 'PARTY/SET_LOADING';